### ISSUE TITLE
回调调试报404

### ISSUE THREAD

**Issue by subtle01** [UmfintechWtc/wechat#1]
你好，运行之后进行调试，报404，调试失败是什么原因

**Comment by zerotocode398** [comment]
404(请求资源不存在)，有打断点吗，在那个环节报的错

**Comment by subtle01** [comment]
> 404(请求资源不存在)，有打断点吗，在那个环节报的错

有一个报错：TypeError: cannot unpack non-iterable NoneType object
然后控制台就提示： "GET /?msg_signature=4b75604e688ec605f4252dd5f51e9961a70353b3&timestamp=1635902305&nonce=twcg02uqxif&echostr=LnMd1EEyy09CSoQxD5CnxNPBfTmRpYOSpWSaKSjJmT5zf%2FuVjJhxldj4JsCsTvfZQDsdp%2FO%2Fp9s4YH%2FCiqh%2FxGSFfgty91akzzl9SHWXHTQXxEL71xT8Kp45sEUHW9%2BQENj5535MqOTwu5UII73%2Fa%2BO2UqNnh3gx6msahIOZGZ0Qq0CFPrAOwaSIOLc0PFMfFL0dGsxBearR60tAv2h4jA%3D%3D HTTP/1.1" 404 -
我是个初学者，这块搜索好些内容没有解决，感谢答复

**Comment by subtle01** [comment]
刚看了下官方文档，验证url好像少传了一个参数sReplyEchoStr

**Comment by zerotocode398** [comment]
返回的对象不可迭代
